Avoid `gem build` error
* Use more specific version requirements.
* Use `>=` instead of `==` for Ruby version check.

Fixes:

    ERROR:  Error installing
    /Users/croaky/github.com/thoughtbot/suspenders/pkg/suspenders-1.13.0.gem:
            suspenders requires Ruby version = 2.1.2.